### ISSUE TITLE
More of a request

### ISSUE THREAD

**Issue by tobeypeters** [VPKSoft/ScintillaLexers#1]
Could we get a small sample application, to see how to use your ScintillaLexers?

**Comment by VPKSoft** [comment]
Hi,
I added the test application to the repository.
Basically it is as simple as this:
```cs
        private void mnuOpen_Click(object sender, EventArgs e)
        {
            if (odFile.ShowDialog() == DialogResult.OK)
            {                
                scintilla.Text = File.ReadAllText(odFile.FileName);

                string fileName = @"C:\Program Files (x86)\Notepad++\stylers.model.xml";

                ScintillaLexers.CreateLexerFromFile(scintilla, odFile.FileName, fileName);
            }
        }
```

![image](https://user-images.githubusercontent.com/40712699/57568072-f61abe00-73ea-11e9-84e2-740761c50b3c.png)

**Comment by VPKSoft** [comment]
Closing because of no reaction from the user who asked the question.
