### ISSUE TITLE
CSS files visualization problem

### ISSUE THREAD

**Issue by lgaudouen** [VPKSoft/ScintillaLexers#33]
Testing this particularly interesting program, I loaded CSS files with always the same visualization problem.
Would you have the solution?
![cssIssue](https://github.com/VPKSoft/ScintillaLexers/assets/5849176/db75b662-5511-418d-8764-0574bc88c388)

**Comment by VPKSoft** [comment]
Hi,
I don't have a direct solution for that issue which seems to draw the white-space in black background but I'll take a look.
Also mentioned in [Scintilla.NET](https://github.com/VPKSoft/Scintilla.NET/issues/71).

**Comment by lgaudouen** [comment]
**I sais you:**
"After days of unsuccessful attempts to use the VPK package Scintilla.NET for CSS files, I found the VPK project ScintillaLexers-v.1.1.15 which was to bring me the solution to the configuration of Scintilla and the Css lexer (with in addition the recovery of Notepad++ parameters).
Unfortunately, the display of a css file by TestLexer is incorrect (see image).
Would you have the solution?"
**Your response about Scintilla.Net:**
Hi,
I don't have a direct solution for that issue which seems to draw the white-space in black background but I'll take a look. Also this is not Scintilla.NET issue so closing this here.
**Now**:
There are not only white-spaces but also EoLs.
Also, not all whitespaces are displayed as black characters.
You say it's not a Scintilla.NET problem, so you think it's a scintilla-lexilla problem.
However, SciTE does not present the same problem and integrates the same source of the CSS lexer. By replacing the scintilla and lexilla dlls for Scintilla.NET with the latest versions (lexilla: 5.2.6 and scintilla: 5.3.6, also used by Nodepad++), I still have the same problem with Scintilla.Net.
Have you really tested Scintilla.NET with a CSS file?
Another possibility: the problem comes from ScintillaLexers for the configuration of the call to the CSS lexer.
When I have a little more time, I will look Scintilla.NET.

**Comment by lgaudouen** [comment]
A solution:
In the VPKSoft.ScintillaLexers.NET project, the LexerColors file, around line 870, we can read:
         new[]
         {
              Tuple.Create(Color.FromArgb(0, 0, 0), "DEFAULT", true), // #000000
             Tuple.Create(Color.FromArgb(255, 255, 255), "DEFAULT", false), // #FFFFFF
...

By reversing the two lines to have:
         new[]
         {
             Tuple.Create(Color.FromArgb(255, 255, 255), "DEFAULT", false), // #FFFFFF --> background
             Tuple.Create(Color.FromArgb(0, 0, 0), "DEFAULT", true), // #000000 --> foreground

it works.

For what ? : I didn't look any further and I let you find the reason for this curiosity.

**Comment by VPKSoft** [comment]
Hi,
Seems to be that there is a **bug** in the internal color config for CSS which you found and fixed 👍 Would you like to create a PR for the fix? If not I can do so also within a week or two...

**Comment by lgaudouen** [comment]
What I had done was only a workaround and not a fix.
In fact, the bug comes from the CreateCssLexer function (CreateLexerCss.cs):
```
         // DEFAULT, fontStyle = 0, styleId = 0
         scintilla.Styles[Style.Css.Default].ForeColor = lexerColors[LexerType.Css, "DefaultFore"];
         scintilla.Styles[Style.Css.Default].BackColor = lexerColors[LexerType.Css, "DefaultFore"];
```
Instead of :
`         scintilla.Styles[Style.Css.Default].BackColor = lexerColors[LexerType.Css, "DefaultBack"];
`

Moreover, being very (VERY) interested in the various packages that you publish, I have several questions, remarks and suggestions to make to you that I could communicate to you by another way than "
Petteri Kautonen <notifications@github.com>".
At your disposal.

**Comment by VPKSoft** [comment]
Okay, anyhow the bug is found, which means it can be fixed. I don't do social media, i.e. stuff but you can skype me: [skype:live:.cid.5e37f7eaca5d5902?chat](skype:live:.cid.5e37f7eaca5d5902?chat)...

**Comment by lgaudouen** [comment]
No social media, no skype, no chats, just thought-provoking text. Since you're the author, I don't need the publicity that comes with posting to systems like the one provided by github.com. 

For other problems and suggestions, I will see. 

Sincerely.

 

De : Petteri Kautonen ***@***.***> 
Envoyé : lundi 21 août 2023 18:49
À : VPKSoft/ScintillaLexers ***@***.***>
Cc : lgaudouen ***@***.***>; Author ***@***.***>
Objet : Re: [VPKSoft/ScintillaLexers] CSS files visualization problem (Issue #33)

 

Okay, anyhow the bug is found, which means it can be fixed. I don't do social media, i.e. stuff but you can skype me: skype:live:.cid.5e37f7eaca5d5902?chat...

**Comment by VPKSoft** [comment]
Alight, [email](mailto:petteri.kautonen@vpksoft.net) it is then.

**Comment by VPKSoft** [comment]
Hi,
I fixed the issue a NuGet package should be available soon - thanks for the help.
